# Generated by Django 4.2.3 on 2023-07-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('rating', models.CharField(max_length=128)),
            ],
        ),
    ]
